services:
  - type: web
    name: multimodal-pdf-rag-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: EURI_API_KEY
        sync: false
      - key: VECTOR_DB_TYPE
        value: chroma
      - key: LOG_LEVEL
        value: INFO
    disk:
      name: pdf-storage
      mountPath: /app/uploads
      sizeGB: 10

  - type: web
    name: multimodal-pdf-rag-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://multimodal-pdf-rag-backend.onrender.com
      - key: NODE_VERSION
        value: 18.17.0

databases:
  - name: pdf-rag-db
    databaseName: pdf_rag
    user: pdf_user